# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-03 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employer',
            name='employer_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='freelancer.Employer_type'),
        ),
    ]
