# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_auto_20191003_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
