# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_freelancer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='years_experience',
            field=models.IntegerField(null=True),
        ),
    ]
