# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0004_freelancer_years_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='profile_picture/default_profile.jpg', upload_to='profile_picture/'),
        ),
    ]
