# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-16 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0007_auto_20191016_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='No title', max_length=100),
        ),
    ]
