# Generated by Django 2.2.6 on 2019-10-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0011_project_applied_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='language',
            field=models.ManyToManyField(null=True, related_name='freelancer_language', to='freelancer.Language'),
        ),
    ]
