# Generated by Django 2.2.6 on 2019-10-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0012_auto_20191022_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='profile_picture/user-image.png', upload_to='profile_picture/'),
        ),
    ]
