# Generated by Django 2.2.6 on 2019-10-30 14:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0014_auto_20191022_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, null=True)),
                ('payment_date', models.DateField(default=datetime.datetime.now)),
                ('release_date', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_employer_user', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_freelancer_user', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.Project')),
            ],
        ),
    ]
